#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libbluray
Version  : 1.1.2
Release  : 1
URL      : https://download.videolan.org/pub/videolan/libbluray/1.1.2/libbluray-1.1.2.tar.bz2
Source0  : https://download.videolan.org/pub/videolan/libbluray/1.1.2/libbluray-1.1.2.tar.bz2
Summary  : library supporting Blu-ray playback
Group    : Development/Tools
License  : LGPL-2.1+
Requires: libbluray-bin = %{version}-%{release}
Requires: libbluray-data = %{version}-%{release}
Requires: libbluray-lib = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : doxygen
BuildRequires : graphviz
BuildRequires : openjdk
BuildRequires : perl
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(libxml-2.0)

%description
Disclaimer
----------
This library is written for the purpose of playing Blu-ray movies. It is
intended for software that want to support Blu-ray playback (such as VLC and
MPlayer). We, the authors of this library, do not condone nor endorse piracy.

%package bin
Summary: bin components for the libbluray package.
Group: Binaries
Requires: libbluray-data = %{version}-%{release}

%description bin
bin components for the libbluray package.


%package data
Summary: data components for the libbluray package.
Group: Data

%description data
data components for the libbluray package.


%package dev
Summary: dev components for the libbluray package.
Group: Development
Requires: libbluray-lib = %{version}-%{release}
Requires: libbluray-bin = %{version}-%{release}
Requires: libbluray-data = %{version}-%{release}
Provides: libbluray-devel = %{version}-%{release}
Requires: libbluray = %{version}-%{release}

%description dev
dev components for the libbluray package.


%package lib
Summary: lib components for the libbluray package.
Group: Libraries
Requires: libbluray-data = %{version}-%{release}

%description lib
lib components for the libbluray package.


%prep
%setup -q -n libbluray-1.1.2
cd %{_builddir}/libbluray-1.1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586980353
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1586980353
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bd_info

%files data
%defattr(-,root,root,-)
/usr/share/java/libbluray-awt-j2se-1.1.2.jar
/usr/share/java/libbluray-j2se-1.1.2.jar

%files dev
%defattr(-,root,root,-)
/usr/include/libbluray/bluray-version.h
/usr/include/libbluray/bluray.h
/usr/include/libbluray/clpi_data.h
/usr/include/libbluray/filesystem.h
/usr/include/libbluray/keys.h
/usr/include/libbluray/log_control.h
/usr/include/libbluray/meta_data.h
/usr/include/libbluray/overlay.h
/usr/include/libbluray/player_settings.h
/usr/lib64/libbluray.so
/usr/lib64/pkgconfig/libbluray.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libbluray.so.2
/usr/lib64/libbluray.so.2.1.2
